pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        sh 'docker build -t phoom005/devops_mern_backend:1.0 ./backend'
        sh 'docker build -t phoom005/devops_mern_frontend:1.0 ./frontend'
      }
    }
    stage('Push') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
          sh 'echo $PASS | docker login -u $USER --password-stdin'
          sh 'docker push phoom005/devops_mern_backend:1.0'
          sh 'docker push phoom005/devops_mern_frontend:1.0'
        }
      }
    }
    stage('Deploy to K8s') {
      steps {
        sh 'kubectl apply -f k8s/'
      }
    }
  }
}
